#!/bin/bash
REGION='eu-west-1'
CUSTOMER_ID='033269891345'
BUCKET_NAME_TO_UPLOAD='testujem-video-upload'
BUCKET_NAME_FOR_VIDEOS='testujem-video-stream'
TRANSCODER_PRESSET_NAME='testing_transcoder_presset'
VIDEO_UPLOADING_POLICY_NAME='testing_uploading_policy_name'
TRANSCODER_ROLE_NAME='testing_transcoder_role'
TRANSCODER_PIPELINE_NAME='testing_pipeline'
LAMBDA_ROLE_NAME='testing_lambda_role'
LAMBDA_LOGGING_POLICY_NAME='testing_lambda_logging_policy'
LAMBDA_GET_UPLOAD_URL_NAME='testing_lambda_get_upload_url'
AUTH_DOMAIN='studivz.vinidev.com'

SUB_TEMPLATE="s/TEMPLATE_REGION/$REGION/g; 
s/TEMPLATE_CUSTOMER_ID/$CUSTOMER_ID/g;
s/TEMPLATE_BUCKET_NAME_TO_UPLOAD/$BUCKET_NAME_TO_UPLOAD/g; 
s/TEMPLATE_BUCKET_NAME_FOR_VIDEOS/$BUCKET_NAME_FOR_VIDEOS/g;
s/TEMPLATE_BUCKET_NAME_FOR_THUMBNAILS/$BUCKET_NAME_FOR_VIDEOS/g;
s/TEMPLATE_TRANSCODER_PRESSET_NAME/$TRANSCODER_PRESSET_NAME/g;
s/TEMPLATE_VIDEO_UPLOADING_POLICY_NAME/$VIDEO_UPLOADING_POLICY_NAME/g;
s/TEMPLATE_TRANSCODER_ROLE_NAME/$TRANSCODER_ROLE_NAME/g;
s/TEMPLATE_TRANSCODER_PIPELINE_NAME/$TRANSCODER_PIPELINE_NAME/g;
s/TEMPLATE_LAMBDA_ROLE_NAME/$LAMBDA_ROLE_NAME/g;
s/TEMPLATE_LAMBDA_LOGGING_POLICY_NAME/$LAMBDA_LOGGING_POLICY_NAME/g;
s/TEMPLATE_LAMBDA_GET_UPLOAD_URL_NAME/$LAMBDA_GET_UPLOAD_URL_NAME/g;
s/TEMPLATE_AUTH_DOMAIN/$AUTH_DOMAIN/g;"

sed "$SUB_TEMPLATE" create_stack.template>create_stack
sed "$SUB_TEMPLATE" delete_stack.template>delete_stack

sed "$SUB_TEMPLATE" ../iam/upload-s3-policy.json.template>../iam/upload-s3-policy.json

sed "$SUB_TEMPLATE" ../iam/stream-s3-policy.json.template>../iam/stream-s3-policy.json

sed "$SUB_TEMPLATE" ../iam/upload-policy.json.template>../iam/upload-policy.json

sed "$SUB_TEMPLATE" ../iam/lambda-log-policy.json.template>../iam/lambda-log-policy.json

chmod 755 create_stack
chmod 755 delete_stack